name: SQL for GitHub Actions

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: windows-latest
        # steps:
        #  - uses: actions/checkout@v1
        #  - uses: azure/login@v1
        #    with:
        #     creds: ${{ secrets.AZURE_CREDENTIALS }}
        #  - uses: azure/sql-action@v2
        #    with:
        #     connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        #     path: './dbDefinition/*.sql'


        defaults:
            run:
                working-directory: ./dbDefinition
        steps:
        - name: Log in
        - uses: actions/checkout@v1
        - uses: azure/login@v1 
        - name: Run a table creation
        - run: ./CreateTables.sql
        - name: Run constraints
        - run: ./TableConstarints.sql
    
    # # Azure logout 
    #  - name: logout
    #    run: |
    #           az logout
